### ISSUE TITLE
GetOptionHistory fails to work with option created by Symbol.CreateOption()

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Research#13]
Currently, the functionality of GetOptionHistory() works only with universes, not single Options which can be created by Symbol.CreateOption(). The code below, run in the QC research environment, can recreate the issue
```qb = QuantBook()
#amzn = qb.AddEquity("AMZN")
amzn = qb.AddOption('AMZN')
amzn_specific = Symbol.CreateOption('AMZN',Market.USA,OptionStyle.American,OptionRight.Call,1665,datetime(2018,12,21))
amzn.SetFilter(-2, 2, timedelta(0), timedelta(180))
print(amzn_specific)
history = qb.GetOptionHistory(amzn_specific, datetime(2018,11,29))
```

**Comment by Martin-Molinero** [comment]
The following seems to work for me in the current research environment 
```
option = qb.AddOption('AMZN')
amzn_specific = Symbol.CreateOption('AMZN',Market.USA,OptionStyle.American,OptionRight.Call,1665,datetime(2018,12,21))
print(qb.History(amzn_specific, datetime(2018,11,29), datetime(2018,11,30), Resolution.Minute))
print(amzn_specific)
```

For a specific contract we can directly call `qb.History()`. `qb.GetOptionHistory()` is a helper method that for a canonycal option Symbol (eg `amzn = qb.AddOption('AMZN').Symbol`) will determine the contract list and call `qb.History()`: 
```
amzn = qb.AddOption('AMZN')
print(qb.GetOptionHistory(amzn.Symbol, datetime(2018,11,29)).GetAllData())
```
