### ISSUE TITLE
Enable Weekly Options Access

### ISSUE THREAD

**Issue by simonsonjack** [QuantConnect/Research#14]
Both of the code snippets below should return weekly options data, but instead, they return a `NullReferenceException`. This issue stems for this forum thread: https://www.quantconnect.com/forum/discussion/4552/weekly-options-in-notebook/p1

```
class MyQuantBook(QuantBook):
def UniverseFunc(self, universe):
return universe.IncludeWeeklys().Strikes(-2, 2).Expiration(timedelta(0), timedelta(365*2))
qb = MyQuantBook()
spy = qb.AddOption("GOOG")
spy.SetFilter(qb.UniverseFunc)
```

```
qb = QuantBook()

def UniverseFunc(self, universe):
        return universe.IncludeWeeklys().Strikes(-8, 8).Expiration(timedelta(25), timedelta(35))
qb.AddEquity("SPY", Resolution.Daily)
spy = qb.AddOption("SPY", Resolution.Daily)
spy.SetFilter(UniverseFunc)
```

**Comment by yellowandy** [comment]
In the past options data wasn't available at the daily granularity, could that be part of the issue?

**Comment by jaredbroad** [comment]
Solved by Frontline.
https://www.quantconnect.com/forum/discussion/4552/weekly-options-in-notebook/p1
