### ISSUE TITLE
Upgrade Plotly to 4.0.0 version

### ISSUE THREAD

**Issue by AlinXlin** [QuantConnect/Research#17]
Currently, using the `plotly.graph_objs` package throws an error `AttributeError: 'Figure' object has no attribute 'show'` when trying to plot candlestick chart using the following code block.

```
import plotly.graph_objs as go
fig = go.Figure(data=[go.Candlestick(x=h1['open'].index,
                                    open = h1['open'],
                                    high = h1['high'],
                                    low = h1['low'],
                                    close = h1['close'])])
fig.show()
```

A possible solution is to upgrade `plotly` package to 4.0.0 version in RE as suggested on [stackoverflow](https://stackoverflow.com/questions/57242997/figure-object-has-no-attribute-show)

**Comment by Martin-Molinero** [comment]
Plotly has been updated in the new research enviroment! 
![image](https://user-images.githubusercontent.com/18473240/66613277-4e710a00-eb9b-11e9-986a-7abc5f4c0454.png)

Tested `fig.show()` is not throwing and is working now. Closing this issue
