### ISSUE TITLE
History calls crash kernel

### ISSUE THREAD

**Issue by worthy7** [QuantConnect/Research#9]
after subscribing, I call this code.

`qb.History(["EURUSD"], datetime(2015,1,1), datetime.now(), Resolution.Daily)`
It runs no problem. But if I run it 5 times, it crashes the kernel on the 5th time.

The error seems to be : `Fatal Python error: deallocating None`

> Fatal Python error: deallocating None
> 
> Thread 0x000064dc (most recent call first):
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\parentpoller.py", line 97 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 916 in _bootstrap_inner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 884 in _bootstrap
> 
> Thread 0x00005184 (most recent call first):
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 295 in wait
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 551 in wait
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\history.py", line 829 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\history.py", line 58 in needs_sqlite
>   File "<decorator-gen-24>", line 2 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 916 in _bootstrap_inner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 884 in _bootstrap
> 
> Thread 0x00007274 (most recent call first):
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\heartbeat.py", line 61 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 916 in _bootstrap_inner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 884 in _bootstrap
> 
> Thread 0x00005acc (most recent call first):
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\selectors.py", line 314 in _select
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\selectors.py", line 323 in select
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\asyncio\base_events.py", line 1398 in _run_once
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\asyncio\base_events.py", line 422 in run_forever
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\platform\asyncio.py", line 132 in start
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\iostream.py", line 78 in _thread_main
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 864 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 916 in _bootstrap_inner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\threading.py", line 884 in _bootstrap
> 
> Current thread 0x00005c80 (most recent call first):
>   File "<ipython-input-8-0b3471a6f204>", line 1 in <module>
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\interactiveshell.py", line 3267 in run_code
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\interactiveshell.py", line 3191 in run_ast_nodes
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\interactiveshell.py", line 3020 in run_cell_async
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\async_helpers.py", line 67 in _pseudo_sync_runner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\interactiveshell.py", line 2845 in _run_cell
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\core\interactiveshell.py", line 2819 in run_cell
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\zmqshell.py", line 536 in run_cell
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\ipkernel.py", line 294 in do_execute
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\gen.py", line 326 in wrapper
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\kernelbase.py", line 534 in execute_request
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\gen.py", line 326 in wrapper
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\kernelbase.py", line 267 in dispatch_shell
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\gen.py", line 326 in wrapper
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\kernelbase.py", line 357 in process_one
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\gen.py", line 1147 in run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\gen.py", line 1233 in inner
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\stack_context.py", line 300 in null_wrapper
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\ioloop.py", line 758 in _run_callback
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\asyncio\events.py", line 145 in _run
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\asyncio\base_events.py", line 1434 in _run_once
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\asyncio\base_events.py", line 422 in run_forever
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tornado\platform\asyncio.py", line 132 in start
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\kernelapp.py", line 505 in start
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\traitlets\config\application.py", line 658 in launch_instance
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel_launcher.py", line 16 in <module>
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 85 in _run_code
>   File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 193 in _run_module_as_main
> [I 12:00:05.236 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports

Code proving history is causing the crash:
```
%matplotlib inline
# Imports
from clr import AddReference
AddReference("System")
AddReference("QuantConnect.Common")
AddReference("QuantConnect.Jupyter")
AddReference("QuantConnect.Indicators")
from System import *
from QuantConnect import *
from QuantConnect.Data.Market import TradeBar, QuoteBar
from QuantConnect.Jupyter import *
from QuantConnect.Indicators import *
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from math import ceil, floor
# Create an instance
qb = QuantBook()
plt.style.use('seaborn-whitegrid')
qb.AddForex("EURUSD")
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
```

Separate issue which may be the same cause: This case will also cause a crash
```
qb = QuantBook()
qb.AddForex("EURUSD")
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
qb = QuantBook()
qb.AddForex("EURUSD")
qb.History(["EURUSD"], datetime(2010,1,1), datetime.now(), Resolution.Daily)
```

**Comment by jaredbroad** [comment]
Thanks @Worthy7 its likely an old version of pythonnet with memory leaks. We'll confirm its updated and circle back here.

**Comment by Worthy7** [comment]
Could I get an update please - or if someone could point me in the direction to fix it myself that would be appreciated thanks.

**Comment by simonsonjack** [comment]
Large history calls still crash the kernel even with most recent pythonnet. The code below is the maximum amount of futures data (in terms of rows returns when accessing all data via GetAllData()) that can be retrieved without crashing.
```
qb = QuantBook()
es  = qb.AddFuture("ES")
es.SetFilter(timedelta(0), timedelta(180))
future_history = qb.GetFutureHistory(es.Symbol, datetime(2017, 1, 11, 10, 10), datetime(2017, 1, 13, 5, 19, 59))
print(future_history.GetAllData().info())
```

This means that the example for Futures data in the documentation [section ](https://www.quantconnect.com/docs/research/historical-data) fails to properly execute.

**Comment by simonsonjack** [comment]
It's in the cloud

**Comment by Worthy7** [comment]
How do you know what version of PythonNet the Cloud is using?

>

**Comment by Worthy7** [comment]
@simonsonjack Given that you added that label, I'm guessing you work for QC and know what version it is?
Either way, I can confirm that I have fixed my local version simply by doing this again (from the Junpyter folder [readme](https://github.com/QuantConnect/Lean/tree/master/Jupyter))

```
   git clone https://github.com/QuantConnect/pythonnet
   cd pythonnet
   python setup.py install
```

**Comment by simonsonjack** [comment]
Yes, I’m part of the QuantConnect team. I’m confirming with our engineers about the version of PythonNet in the cloud but I’m glad to hear it’s worked out for you in Lean

**Comment by dojibarfly** [comment]
I still cannot get a dataframe that is not empty:
![image](https://user-images.githubusercontent.com/50810701/62013015-159bca00-b142-11e9-8dd5-ad6492311c64.png)
Now what? Are you folks doing anything to fix this?
8 months and this still doesn't work!
